### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by tak-fomalhaut** [yukifu027/fleamarket_sample_75b#52]
■ URL
IPアドレス：54.168.141.53
Github（最終課題のリポジトリ）：https://github.com/yukifu027/fleamarket_sample_75b

■ Basic認証
ID：furima75b
Pass：techcamp75

■ テスト用アカウント
◯ 購入者用
メールアドレス：taro75@gmail.com
パスワード：NYN0rsnD

◯ 購入用カード情報
番号：5105105105105100
期限：01/23
セキュリティカード：123

◯ 出品者用
メールアドレス：testkun@gmail.com
パスワード：testkun1111

**Comment by tak-fomalhaut** [comment]
## notice
チーム一同個人アプリなどには手をつけずに最終課題のみに集中して作成いたしました。
少し早く終わっているのはまだ個人アプリに手をつけていない人もいるので、その後の期間を個人アプリ作成に当てるためです。
おそらく個人アプリを作りながらやっていたら12日ギリギリになっていたかと思います。
どうぞ優しいお心持ちでレビューお願いします笑

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
チーム一丸となって作成する姿勢、とても素晴らしいです✨
おつかれさまでした！！
ただし、以下の通り修正いただきたい箇所がございます。
ご確認をよろしくお願いします！

**[修正依頼箇所]**
### ○商品出品時、カテゴリーが一つしか選択できない為、子カテゴリー及び孫カテゴリーを入力できるようにしましょう。また、編集及び表示する際にも孫カテゴリーまで表示されるようにしましょう！

修正し次第、以下の最終課題完了報告フォームを再度ご提出して下さい！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by tak-fomalhaut** [comment]
> ご提出ありがとうございます！
> チーム一丸となって作成する姿勢、とても素晴らしいですね✨
> おつかれさまでした！！
> ただし、以下の通り修正いただきたい箇所がございます。
> ご確認をよろしくお願いします！
> 
> **[修正依頼箇所]**
> 
> ### ○商品出品時、カテゴリーが一つしか選択できない為、子カテゴリー及び孫カテゴリーを加えましょう。また、編集及び表示する際にも孫カテゴリーまで表示されるようにしましょう！
> 修正し次第、以下の最終課題完了報告フォームを再度ご提出して下さい！
> https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by mutorisa** [comment]
修正後、再度ご提出ありがとうございます✨
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
